{
 "title": "RED Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_server_duration_count, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{job=\"$instance\", http_status_code=~\"5..\"}[5m])) / sum(rate(http_server_duration_count{job=\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_duration_bucket{job=\"$instance\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_duration_bucket{job=\"$instance\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_server_duration_bucket{job=\"$instance\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}